name: plantsafe
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26=haa95532_2
  - certifi=2021.10.8=py37haa95532_0
  - openssl=1.1.1l=h2bbff1b_0
  - pip=21.2.4=py37haa95532_0
  - python=3.7.11=h6244533_0
  - setuptools=58.0.4=py37haa95532_0
  - sqlite=3.37.0=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - wincertstore=0.2=py37haa95532_2
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - bcrypt==3.2.0
    - cached-property==1.5.2
    - cachetools==4.2.4
    - cffi==1.15.0
    - charset-normalizer==2.0.9
    - click==8.0.3
    - colorama==0.4.4
    - cycler==0.11.0
    - flask==2.0.2
    - flask-cors==3.0.10
    - flask-marshmallow==0.14.0
    - flask-sqlalchemy==2.5.1
    - flatbuffers==2.0
    - fonttools==4.28.5
    - gast==0.4.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==1.1.2
    - grpcio==1.43.0
    - h5py==3.6.0
    - idna==3.3
    - importlib-metadata==4.10.0
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - joblib==1.2.0
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==12.0.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - marshmallow==3.14.1
    - matplotlib==3.5.1
    - mouse==0.7.1
    - mysqlclient==2.1.0
    - numpy==1.21.5
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - opt-einsum==3.3.0
    - packaging==21.3
    - pillow==9.3.0
    - protobuf==3.19.1
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pymysql==1.0.2
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - six==1.16.0
    - slidingwindow==0.0.14
    - sqlalchemy==1.4.29
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - zipp==3.7.0
prefix: C:\Users\Admin\anaconda3\envs\plantsafe
